// <auto-generated />
namespace Movie_Store_MVC_5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createMembershipTypeTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createMembershipTypeTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202106130905188_createMembershipTypeTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
